### ISSUE TITLE
Application Not Working

### ISSUE THREAD

**Issue by mehrdadsafari** [nioc/xmpp-web#113]
### Describe the bug

This Error For Run App : 
Error: No match for
 {"query":{},"hash":"","params":{"pathMatch":""},"name":"home","state":{},"replace":false}
 Please Help Me

### XMPP-web version

0.10.0

### Installation

Build from source

### XMPP server(s)

Openfire

### Browser(s)

Chrome

### Device(s)

desktop

**Comment by mehrdadsafari** [comment]
> ### Describe the bug
> This Error For Run App : Error: No match for {"query":{},"hash":"","params":{"pathMatch":""},"name":"home","state":{},"replace":false} Please Help Me
> 
> ### Steps to reproduce
> _No response_
> 
> ### Expected behavior
> This Error For Run App : Error: No match for {"query":{},"hash":"","params":{"pathMatch":""},"name":"home","state":{},"replace":false} Please Help Me
> 
> ### Relevant log
> _No response_
> 
> ### local.js configuration
> _No response_
> 
> ### XMPP-web version
> 0.10.0
> 
> ### Installation
> Build from source
> 
> ### XMPP server(s)
> Openfire
> 
> ### Browser(s)
> Chrome
> 
> ### Device(s)
> desktop
> 
> ### Other information
> _No response_

**Comment by nioc** [comment]
I have no idea what you are doing/asking.
