### ISSUE TITLE
Docker install uses localhost as ws endpoint despite having it set to something else

### ISSUE THREAD

**Issue by codingneko** [nioc/xmpp-web#114]
Hi, I installed xmpp-web using the provided docker-compose file, and replacting the host port in it with 8086 and proxying it through nginx, I'm not sure which websocket url I am supposed to provide in XMPP_WS so I assumed it's my XMPP server's but it looks like it's not updating it at all and it just uses localhost regardless of what I put here.
My docker-compose.yml looks like this
```YAML
version: "3.4"
services:
  xmpp-web:
    image: nioc/xmpp-web:latest
    ports:
      - "8086:80"
    environment:
      - XMPP_WS=https://chat.catboy.baby/xmpp-websocket
      - APP_DEFAULT_DOMAIN=chat.catboy.baby
 ```
And my nginx config looks like this:

```
server {
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/catboy.baby-0001/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/catboy.baby-0001/privkey.pem;

  server_name web.chat.catboy.baby;

  location / {
      proxy_pass http://127.0.0.1:8086;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_redirect off;

      # For WebSocket
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
  }
}
```
This is the error I'm getting in the Firefox console:
![image](https://github.com/nioc/xmpp-web/assets/11065075/5780d19f-cad6-4d2e-a717-a12ce4e87601)

Can I get some help please? 🥺 
If you want to have a look yourselves, it's over at https://web.chat.catboy.baby and the ws endpoint is https://chat.catboy.baby/xmpp-websocket

**Comment by codingneko** [comment]
Nevermind, apologies, I'm at the office, and apparently my office network was blocking my subdomain in a weird way so that I could still access it but I couldn't connect to any XMPP servers... Very odd

**Comment by perzarys** [comment]
Hi, I'm facing the exact same issue as the OP. I'm running a Snikket server and https://chat.mydomain.tld/xmpp-websocket returns the familiar message "Prosody WebSocket endpoint - It works! Now point your WebSocket client to this URL to connect to Prosody."

Logging in with xmpp web does not work however, and gives me this error:

![image](https://github.com/user-attachments/assets/75ea2048-9d35-4d7a-9cfa-fdd77a24bb1d)

So apparently the XMPP_WS environment variable I set does not override the default `localhost/xmpp-websocket`?

I use nginx-proxy-manager, and enable websocket support + HTTP/2 support in its GUI. Do I need to setup something else there, maybe?


My config:
```yaml
services:
  xmpp-web:
    container_name: xmpp-web
    image: nioc/xmpp-web:latest
    environment:
      - XMPP_WS=https://chat.mydomain.tld/xmpp-websocket
      - APP_DEFAULT_DOMAIN=chat.mydomain.tld
```

Any help is appreciated.

**Comment by perzarys** [comment]
I've made some progress by setting `APP_WS=wss://chat.mydomain.tld/xmpp-websocket`, but I get this error now:

![image](https://github.com/user-attachments/assets/524a1513-7172-484a-bc25-5cfa4537fae4)

Didn't find much at all on the internet about this error.
I've tried converse.js web client as well and I could immediately login. So I'm not sure what's wrong here.

**Comment by nioc** [comment]
Hello @perzarys, websocket used from GUI is set by `APP_WS` env var, which should be nginx for proxy pass the `XMPP_WS` var.
So if you're running the GUI on a dns "chat.mydomain.ltd" the APP_WS should be set to `ws://chat.mydomain.ltd/xmpp-websocket`, then nginx will proxify to XMPP_WS, let's say `http://localhost:5280/xmpp-websocket` if Prosody is on the same host.

**Comment by nioc** [comment]
For auth mechanism, you can refer to the [XMPP library used](https://github.com/xmppjs/xmpp.js/tree/main/packages/client#authentication)

**Comment by perzarys** [comment]
Hi @nioc, thanks for you reply. I'm not sure how to proceed from here, or what to take away from the link about auth mechanisms you sent. Is there any config change I need to make?

**Comment by nioc** [comment]
It depends how you have configured your prosody instance,you can have a look to [this](docs/staging-environments/prosody-std/prosody.cfg.lua)

**Comment by isaitgirl** [comment]
No matter what I set in docker-compose as env, the application is always trying to reach ws://localhost/xmpp-websocket.

Considering my domain is mychat.im (prosody 13.0.4 xmpp service, correctly working behind nginx) and mychat.cc (web/xmpp-web).

I have this:
```
environment:
      - XMPP_WS=https://mychat.im/xmpp-websocket
      - APP_WS=wss://xmpp-web.mychat.cc/xmpp-websocket
      - APP_DEFAULT_DOMAIN=mychat.im
```

Application insists in reach localhost :( 

I don't wanna give up trying xmpp-web again :) 

<img width="1347" height="111" alt="Image" src="https://github.com/user-attachments/assets/b37e99a7-1101-4caf-a89e-9e3f17e0b86e" />

**Comment by nioc** [comment]
Hello @isaitgirl,
Can you check the value of `transports.websocket` inside the container (`grep websocket /usr/share/nginx/html/local.js`)?
Also I suppose you already cleared browser cache (including unsubscribe service workers)?

**Comment by nioc** [comment]
Also try checking the “disable cache” box in the network tab of the browser console (sorry, the screenshot is in French):

<img width="250" height="59" alt="Image" src="https://github.com/user-attachments/assets/99bae2c5-e9f7-43dc-9377-45fdf12a8b13" />

It appears that `local.js` is being aggressively cached 😞

**Comment by isaitgirl** [comment]
Hi!

The loca.js looks like that:
```
var config = {
  name: 'XMPP web',
  transports: {
    websocket: 'ws://localhost/xmpp-websocket',
  },
  ...
```

**Comment by isaitgirl** [comment]
I've manually changed local.js to use websocket address of Prosody directly, and it's working :)

**Comment by nioc** [comment]
This behavior is very strange (`local.js` is [updated on container start](https://github.com/nioc/xmpp-web/blob/master/docs/docker/998-update-local.js.sh#L20)).

Did you override value before (entrypoint script **<ins>replace</ins>** [default value](https://github.com/nioc/xmpp-web/blob/master/public/local.js#L5) by searching `websocket: 'wss://chat.domain-web.ltd/xmpp-websocket'`)?

Also, did you see these lines in container logs:
```
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/998-update-local.js.sh
update local.js with environment variables... done
/docker-entrypoint.sh: Configuration complete; ready for start up
```

Does the variable is set within container: `echo $XMPP_WS` ?

What is your docker engine (docker, podman, ...)?

Last idea, can you try with this syntax (should be the same...):
```yaml
  xmpp-web:
    image: nioc/xmpp-web:latest
    environment:
      XMPP_WS: https://mychat.im/xmpp-websocket
      APP_DEFAULT_DOMAIN: mychat.im
      APP_WS: wss://xmpp-web.mychat.cc/xmpp-websocket
```

**Comment by isaitgirl** [comment]
Startup logs:

```
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/998-update-local.js.sh
update local.js with environment variables... done
/docker-entrypoint.sh: Configuration complete; ready for start up
```

It seems the env replacement is working and transports.websocket now have the desired value.

Thanks for your clarification. :)
