### ISSUE TITLE
Use domain.tld for both XMPP and website

### ISSUE THREAD

**Issue by roughnecks** [nioc/xmpp-web#115]
Hello,

I have my prosody server at woo...t.space and I have my website at the same domain

Is there a way for me to host the webchat, so that it doesn't collide with my website?

I can host at a subdomain, but then my login credential don't work, since it tries to connect to e.g. webchat.woo...t.space, which is not my xmpp server's virtualhost.

**Comment by roughnecks** [comment]
Hi.

came up with this (using nginx) but I still have problems authenticating: https://paste.woodpeckersnest.space/?c7a8446104c74c16#D3sUYFgrpE4WL9AouWRR2SPdMYUMFGCwb3eJeXSNiR45

**Comment by roughnecks** [comment]
This error is repeating in console:

```
index-0eca49fe.js:15 XMPP error WebSocket ECONNERROR ws://localhost/xmpp-websocket
(anonymous) @ index-0eca49fe.js:15
Ye.emit @ index-0eca49fe.js:15
s.error @ index-0eca49fe.js:15
Ye.emit @ index-0eca49fe.js:15
s.error @ index-0eca49fe.js:15
error (async)
_attachSocket @ index-0eca49fe.js:15
connect @ index-0eca49fe.js:15
connect @ index-0eca49fe.js:15
connect @ index-0eca49fe.js:15
TS.t.connect @ index-0eca49fe.js:15
reconnect @ index-0eca49fe.js:15
(anonymous) @ index-0eca49fe.js:15
setTimeout (async)
scheduleReconnect @ index-0eca49fe.js:15
s.disconnect @ index-0eca49fe.js:15
Ye.emit @ index-0eca49fe.js:15
_status @ index-0eca49fe.js:15
s.close @ index-0eca49fe.js:15
Ye.emit @ index-0eca49fe.js:15
s.close @ index-0eca49fe.js:15
index-0eca
```

why does it say localhost?

**Comment by nioc** [comment]
Can you type `window.config.transports.websocket` in console please?

**Comment by nioc** [comment]
On [XmppSocket.js](https://github.com/nioc/xmpp-web/blob/master/src/services/XmppSocket.js#L70), it create a XMPP object with the socket in `service` attribute.
If no value is provided, the [XmppClient.js](https://github.com/nioc/xmpp-web/blob/master/src/services/XmppClient.js#L76) use `ws://localhost:5280/xmpp-websocket` as default.

I'm betting on an error in your local.json file.

**Comment by nioc** [comment]
@roughnecks I think it works now 😉 
![image](https://github.com/nioc/xmpp-web/assets/5225411/fb9d2a69-f0f4-4a98-99d9-f73dc578eaf5)

**Comment by roughnecks** [comment]
> window.config.transports.websocket

'ws://localhost/xmpp-websocket'

did you check my paste? Config is there

**Comment by roughnecks** [comment]
working now, not sure if this line was needed:

`// eslint-disable-next-line no-unused-vars, no-var`

**Comment by nioc** [comment]
Not useful in production, it is for avoid linter complaints.
