### ISSUE TITLE
How can we use it in Nginx webserver

### ISSUE THREAD

**Issue by ebizanil** [nioc/xmpp-web#13]
When I am trying to access it Nginx web server, login is working fine but the contacts and chat options, profile those are not available. Please check it.

**Comment by nioc** [comment]
At first sight, there is no link between web server exposing web app (static js/css files are loaded) and the behavior you described.
Can you give more information about your setup (which XMPP server, which transport,…) ?
Some console logs are welcomed.

**Comment by ebizanil** [comment]
I have created two servers chatserver.domain.com for "XMPP" using https://www.linuxbabe.com/ubuntu/prosody-xmpp-server-ubuntu-18-04
Another chat.domain.com as you code.
When I am trying to log in, I am able to log in but there is online another user to chat

My log:
Jul 27 14:13:35 startup info    Prosody is using the select backend for connection handling
Jul 27 14:13:35 portmanager     info    Activated service 's2s' on [::]:5269, [*]:5269
Jul 27 14:13:35 chatconference.egather.live:tls error   Error creating context for c2s: No certificate present in SSL/TLS configuration for chatconference.egather.live
Jul 27 14:13:35 chatconference.egather.live:tls error   Error creating contexts for s2sin: No certificate present in SSL/TLS configuration for chatconference.egather.live
Jul 27 14:13:35 localhost:groups        info    Groups loaded successfully
Jul 27 14:13:35 portmanager     info    Activated service 'c2s' on [::]:5222, [*]:5222
Jul 27 14:13:35 portmanager     info    Activated service 'legacy_ssl' on no ports
Jul 27 14:13:35 portmanager     info    Activated service 'http' on [::]:5280, [*]:5280
Jul 27 14:13:35 portmanager     info    Activated service 'https' on [::]:5281, [*]:5281
Jul 27 14:13:35 chatserver.egather.live:groups  info    Groups loaded successfully
Jul 27 14:13:35 chatserver.egather.live:websocket       error   cross_domain_websocket = true only works in the global section
Jul 27 14:13:35 chatserver.egather.live:tls     error   Error creating context for c2s: No certificate present in SSL/TLS configuration for chatserver.egather.live
Jul 27 14:13:35 chatserver.egather.live:tls     error   Error creating contexts for s2sin: No certificate present in SSL/TLS configuration for chatserver.egather.live
Jul 27 14:13:37 mod_bosh        info    Client tried to use sid 'e1115596-b9f9-407e-ab68-b3bae2428fca' which we don't know about
Jul 27 14:14:01 mod_bosh        info    New BOSH session, assigned it sid '50f33154-f62b-4028-91ba-3073c40ca660'
Jul 27 14:14:02 bosh50f33154-f62b-4028-91ba-3073c40ca660        info    Authenticated as bwtrofaapntztrtf@chatserver.egather.live
Jul 27 14:14:43 mod_bosh        info    New BOSH session, assigned it sid '998080a7-1808-4c1c-99d0-b846c763def5'
Jul 27 14:14:44 bosh998080a7-1808-4c1c-99d0-b846c763def5        info    Authenticated as 4zydrts8kizie9r9@chatserver.egather.live
Jul 27 14:18:23 mod_bosh        info    New BOSH session, assigned it sid 'f91ee079-eb02-47d4-ac59-829e891dcc85'
Jul 27 14:18:24 boshf91ee079-eb02-47d4-ac59-829e891dcc85        info    Authenticated as myiii2ap11be-aw2@chatserver.egather.live
Jul 27 14:25:52 bosh50f33154-f62b-4028-91ba-3073c40ca660        info    BOSH client disconnected: session close
Jul 27 14:25:52 mod_bosh        info    Client tried to use sid '50f33154-f62b-4028-91ba-3073c40ca660' which we don't know about
Jul 27 14:27:16 mod_bosh        info    New BOSH session, assigned it sid '33dc77ed-31a9-4c2a-a550-c63c5db9d526'
Jul 27 14:32:00 mod_bosh        info    New BOSH session, assigned it sid '5fe7164b-51fb-40e1-a731-3bc499b3e635'
Jul 27 14:32:01 bosh5fe7164b-51fb-40e1-a731-3bc499b3e635        info    Authenticated as cxnedgur2vkns5tn@chatserver.egather.live

**Comment by nioc** [comment]
I'm not sure of understanding.
You installed prosody (I'm using this server too,good choice), set the host to chatserver.domain.com, create a user.
On a second host chat.domain.com you installed nginx and this web app.
Then you can go on chat.domain.com and login with your XMPP credentials.
Do you have any contacts to discuss with (you can create a dummy account on your own xmpp server and add it as a contact) ?
What is the behavior with other xmpp client like pidgin or conversations (Android)?
Can you add *browser* console logs?

**Comment by ebizanil** [comment]
Here is my browser log:

module.js:13992 WebSocket connection to 'wss://chatserver.domain.com/xmpp-websocket' failed: Error during WebSocket handshake: Unexpected response code: 403
connect @ vuex.esm.js:6
(anonymous) @ vuex.esm.js:6
(anonymous) @ chunk-vendors.40ebf1dc.js?__WB_REVISION__=d722a4f8e8d95772d82f:18
i @ chunk-vendors.40ebf1dc.js?__WB_REVISION__=d722a4f8e8d95772d82f:18
connect @ vuex.esm.js:6
(anonymous) @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
connect @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
(anonymous) @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
module.js:13997 Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
(anonymous) @ vuex.esm.js:6
error (async)
connect @ vuex.esm.js:6
(anonymous) @ vuex.esm.js:6
(anonymous) @ chunk-vendors.40ebf1dc.js?__WB_REVISION__=d722a4f8e8d95772d82f:18
i @ chunk-vendors.40ebf1dc.js?__WB_REVISION__=d722a4f8e8d95772d82f:18
connect @ vuex.esm.js:6
(anonymous) @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
connect @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
(anonymous) @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
Promise.then (async)
login @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
submit @ app.40256fa6.js?__WB_REVISION__=30535c4c9060280196af:1
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
(anonymous) @ vue.runtime.esm.js:8
XmppSocket.js:85 socket not work, try bosh {websocket: "wss://chatserver.domain.com/xmpp-websocket", bosh: "https://chatserver.domain.com/http-bind"}

**Comment by nioc** [comment]
Hi,

1. Websocket failed because of your certificate (self signed probably), depending on your browser, you may accept invalid certs. 

2. As websocket failed, you should see in network console some xhr requests to your BOSH endpoint `https://chatserver.domain.com/http-bind`.
One should contains the following query `<query xmlns="jabber:iq:roster" />`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns="http://jabber.org/protocol/httpbind" rid="xxx" sid="xxx">
   <iq xmlns="jabber:client" id="xxx" type="get">
      <query xmlns="jabber:iq:roster" />
   </iq>
</body>
```
The response is your roster (XMPP contacts you add to your current account), they are in an item bloc:
```xml
<item subscription="to" jid="johndoe@domain.ltd" name="JohnDoe" />
```

3. Please check your XMPP setup with an other client.

**Comment by nioc** [comment]
As there was no response since one month, I consider this is not a problem...
