### ISSUE TITLE
SVG version of the XMPPP Web logo

### ISSUE THREAD

**Issue by sjehuda** [nioc/xmpp-web#131]
Good day!

I would be glad to obtain an SVG version of the XMPP Web logo, in order to include it in the list of recommended XMPP client of FASI (an HTML invite page for XMPP.

See https://git.xmpp-it.net/sch/FASI/issues/1

**Comment by nioc** [comment]
The logo I used it the standard XMPP logo without the text. You can found it on [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:XMPP_logo_(without_text).svg).

If necessary, I can send the exact file I used when I open my dev pc.

**Comment by sjehuda** [comment]
Fine. I will enable the XMPP Web entry with the XMPP logo.

Please inform me at any time when this changes.

https://git.xmpp-it.net/sch/FASI/commit/4553e8aa5c05369a1507d77095a7b5e06469aba4

**Comment by sjehuda** [comment]
Is this acceptable?

![xmpp-web](https://github.com/user-attachments/assets/29f106e5-2fdf-4619-8d87-fc75e1c7fdcd)
