### ISSUE TITLE
[UX] Store credentials checkbox label is not clear

### ISSUE THREAD

**Issue by thundergreen** [nioc/xmpp-web#15]
I am using your awesome easy and small web app for my home automation system which I am running at home. This easy web interface allows me to send messages to my dasboard as well as pictures but i have to relogin each time i open this dashboard / page. Is there a way to make the login persisten.. maybe opt in or hardcoded?

Looks like this on my dashboard:

![image](https://user-images.githubusercontent.com/13320319/92812795-3fed2d00-f3c0-11ea-95db-90badb1ef0e5.png)

like this it looks logged in:

![image](https://user-images.githubusercontent.com/13320319/92812932-804cab00-f3c0-11ea-9f33-df0fbcbf5fed.png)

**Comment by nioc** [comment]
Hello, this is the exact purpose of checkbox in login page 😉 
 
![SmartSelect_20200911-014937_Firefox](https://user-images.githubusercontent.com/5225411/92826746-5780e180-f3d1-11ea-8be3-1e1900ce9e00.jpg)

If checked, it does not auto login to your xmpp server?

**Comment by poVoq** [comment]
I think the confusing part is that it says "do not store my password" before the checkbox ;)

**Comment by nioc** [comment]
You're right... I thought a dynamic checkbox label was a good idea but it seems I was wrong 😆
Maybe using a [switch](https://wikiki.github.io/form/switch/) should be more understandable?

**Comment by poVoq** [comment]
Why not just have a static text with a checkbox? That is really the standard everywhere and easily understood.

**Comment by nioc** [comment]
Yep. Agreed for this proposition (return to basic) 👌
@thundergreen can you confirm that with box checked, login is well done?

**Comment by thundergreen** [comment]
Indeed the checkbox seems weird bit works perfectly.tha ks for the hint
