### ISSUE TITLE
[BUG] httpupload not working

### ISSUE THREAD

**Issue by thundergreen** [nioc/xmpp-web#16]
I setup this app with a small docker apache server so far so good but httpupload is not working properly I use bosh and wss configured. any ideawhere to start?

**Comment by nioc** [comment]
I have to remember, where to check logs but first, the browser console log / network response should explain why upload failed.
Can you have a lookat it?

**Comment by nioc** [comment]
I check my own server, XMPP server (Prosody) is configured to allow [HTTP upload](https://modules.prosody.im/mod_http_upload) and it is directly Prosody url/port which are used by browser when I upload file.

For example with following configuration:
- Prosody URL = `domain-xmpp.ltd`
- Prosody HTTPS port = `5281`
- upload slot provided by Prosody = `abcdefgh`

My browser send these requests:
``` HTTP
OPTIONS https://domain-xmpp.ltd:5281/upload/abcdefgh/myfile.png (200)
PUT https://domain-xmpp.ltd:5281/upload/abcdefgh/myfile.png (201)
```

**Comment by thundergreen** [comment]
I'll investigate I guess I have to proxy everything via https .I'll let u know once I figured it out and collected some logs .thanks so far
