### ISSUE TITLE
Anonymous login?

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#19]
Is it possible to configure this to allow a very simple public webinterface for some MUCs that will just ask for a nick and handle temporary accounts through the XMPP server's anonymous login mechanism?

A bit like what happens here with the conversejs instance linked: https://logs.xmpp.org/operators/

Also, can MUCs be deep-linked via a URL? So that several different MUCs could be made available through it via URLs from a website? Edit: or alternatively configure a list of MUCs to auto-join?

Thanks for the help!

**Comment by nioc** [comment]
Hello @poVoq allowing anyone to join public anonymous MUC without login previously seems to be a little difficult in the actual model (since login is required to access other GUI components).
I'm not against a dedicated component if someone propose a pull request 😃

For the second part, it is already possible to access a MUC, let's say you have a room named `conference.domain.ltd`, you can access it directly by passing in the URL the following path `/rooms/{room-jid}`, for example: `https://chat.domain-web.ltd/rooms/welcome@conference.domain.ltd`

**Comment by poVoq** [comment]
It is actually a login mode supported by XMPP servers. It creates a temporary account in the background, see for example: https://prosody.im/doc/anonymous_logins (but ejabberd can also do it).

**Comment by nioc** [comment]
I'm not sure to fully understand the call-flow explained in prosody doc, but here is what I think:
- If anonymous authentication is allowed on XMPP server, user may log without login, nickname, password (jid is provided by server).
- Call-flow is a bit tricky (see the 9 steps described [here](https://xmpp.org/extensions/xep-0175.html#flow)).
- I'm not sure that/ (or how) [StanzaJS](https://github.com/legastero/stanza) library handle it (I searched a bit but I did not see how to call this flow).
- Last but not least : current VueJS app logic requires user login before accessing other GUI components, it implies to edit authentication component and all the logic upon it.

At this time, this enhancement seems to be a long time work...

**Comment by poVoq** [comment]
Hmm, that is a pity because a lightweight web-chat with minimal onboarding barriers might be a really cool use-case for this.

I did find a test for StanzaJS that seems to do login via an anonymous method, might be something else though:
https://github.com/legastero/stanza/blob/d44cda0e79877c49ff26810c6cb35742b1624c33/test/sasl/anonymous.ts

**Comment by nioc** [comment]
Yes, i saw and also mentioned in code [here](https://github.com/legastero/stanza/blob/19dc6ba24dbbefb16cabeb50d3ad6535573701b7/src/Client.ts#L66).
But how to use it... I've not found in library [doc](https://github.com/legastero/stanza/blob/master/docs/Reference.md).

App code use theses 2 functions [XMPP.createClient](https://github.com/nioc/xmpp-web/blob/5512b05e7e0de85d4c82d55d8ca8c51f55066243/src/services/XmppSocket.js#L55) and [client.connect](https://github.com/nioc/xmpp-web/blob/5512b05e7e0de85d4c82d55d8ca8c51f55066243/src/services/XmppSocket.js#L116):
```js
      this.client = XMPP.createClient({
        jid,
        password,
        resource: resource || 'Web XMPP',
        transports: transports || { websocket: true, bosh: true },
      })

      this.client.connect()
```

Let me know if you found how to handle it and I'll see how to adapt app to handle anonymous access.

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by nioc** [comment]
Sunday evening update:

I found how to connect to anonymously using Stanza, it was simple but not documented 😞, just add `server` attribute and remove jid and password:
```js
      this.client = XMPP.createClient({
        server: 'anon.localhost',
        resource: resource || 'Web XMPP',
        transports: transports || { websocket: true, bosh: true },
      })

      this.client.connect()
```
I'll look how to update existing logic (`services/XmppSocket.js`) to reusing it.

Next step will be designing a new "Guest" vue component, here it is a first proposal:
- user access to guest page (with dedicated url, that should contains a room),
- then user auto connect to XMPP server as anonymous guest,
- app request public rooms,
- app display public rooms as list if room was not provided in url or not found in public room list,
- app load room if found in list.

**Comment by poVoq** [comment]
Thanks a lot for working on this!

Maybe some simplified view that disables some features that make little sense for anonymous users could also be configurable? Things like "contacts" and the top left account part.

**Comment by nioc** [comment]
Yep, only chat view will be displayed after joining room.
I think this is a interesting feature but I do not want to break the entire application design 😆

**Comment by Neustradamus** [comment]
@nioc: Thanks, maybe you can see to add more informations in Stanza documentation :)

**Comment by Neustradamus** [comment]
@nioc: Good job, thanks!
Have you planned to see for Stanza doc?

One guy can test it?

**Comment by nioc** [comment]
Hi, work done.
[Here](https://github.com/nioc/xmpp-web/releases/tag/0.6.0) is a 0.6.0 release beta including guest access.
You obviously need an anonymous host on your Prosody and to complete it in `local.js` as `anonymousHost` attribute.

**Comment by nioc** [comment]
@Neustradamus Stanza provide XML abstraction (and it is a huge work) for this app but I do not contribute on it. As author has closed issues, I suppose he is not widely open to contributions... and I do not have time to update third party library documentation 😉

**Comment by nioc** [comment]
Some screenshots in reduced screen size (screenshot is the full app).

Nickname:
![XMPP web-guest-1](https://user-images.githubusercontent.com/5225411/107894909-8e839200-6f31-11eb-9124-956940156c9c.png)

Rooms list:
![XMPP web-guest-2](https://user-images.githubusercontent.com/5225411/107894925-9a6f5400-6f31-11eb-9294-780e2dba05c7.png)

Chat:
![XMPP web-guest-3](https://user-images.githubusercontent.com/5225411/107894930-a0653500-6f31-11eb-8fe3-de8c0315757d.png)


And I forget to say about url:
- guest access: `/guest`
- guest access with requested room: `/guest?join=debug@conference.localhost`
- then when guest joined room: `/guest/debug@conference.localhost`

**Comment by Neustradamus** [comment]
@nioc: Please talk with @legastero here.
But yes, he has removed "Issues" section from repository because I have done several issues.
