### ISSUE TITLE
Display nicks in MUCs?

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#20]
We are testing this cool client right now for anonymous chat on joinjabber.org but I noticed that the nicks in group-chats are not visible.

So you either have to guess by the avatar or hover with the mouse over the avatar to see who actually wrote the message. Especially with a lot of anonymous users (and thus no avatar) this is quite confusing and makes the group-chat not really useable.

Did we miss some setting, or is this not implemented?

**Comment by nioc** [comment]
Hello, I can add nick below the message aside the date. Does this resolve your issue?

**Comment by poVoq** [comment]
Yes, that should be sufficient. Thanks!

**Comment by nioc** [comment]
@poVoq In conjunction with nick display, I am adding an avatar colorization based on the jid, so it will be easier to identify who is writing (releasing in 0.8.1).
