### ISSUE TITLE
xmpp-web assumes it runs in the webroot

### ISSUE THREAD

**Issue by southerntofu** [nioc/xmpp-web#21]
Sidenote: Hello, we're currently trying out xmpp-web for MUC anonymous login for the [joinjabber collective](https://joinjabber.org/). I would like to say a few words to thank you for making it, and let you know i'm going to open a few more issues with specific points about xmpp-web which defied my expectations and/or could be improved. Please don't take it as harsh criticism as i'm already very satisfied with the solution. Sorry i'm not familiar with JavaScript ecosystem in order to propose a patch. Let me know if i should actively try and look for other people to contribute patches.

xmpp-web in index.html has absolute links to `/local.js` and others, which prevents it from running in a subfolder of the webroot (eg `joinjabber.org/xmpp-web`). I believe adding a `base_path = "/xmpp-web/"` setting in local.js would fix this problem.

**Comment by nioc** [comment]
Hello @southerntofu thanks for feedbacks.

I'll look at your issues later, it seems some should be fixed quickly with nginx conf.

What is your setup (nginx/apache local, docker image,…)? Do you use another proxy like HAProxy for https?

**Comment by southerntofu** [comment]
> I'll look at your issues later

Please take all the time you need and don't let yourself be stressed by us :)

> What is your setup

Currently serving with nginx xmpp-web from release tarball, with a `try_files $uri /index.html =404;` rule for SPA routes. I'm no longer running in a subfolder, as i realized (late) that xmpp-web is a single-page application that hijacks the navigation URL somehow. 

> it seems some should be fixed quickly with nginx conf.

I'm skeptical, but very curious :+1:

**Comment by nioc** [comment]
I forgot to commit  following line in `vue.config.js` allowing to acces from a subfolder:
```
publicPath: './',
```
I use this trick to serve multiple versions from nginx (for non regression tests) with following regex in Nginx conf:
```
    location ~ ^(/[^/]+)(.*) {
      root /usr/share/nginx/html;
      try_files $uri $1/$2 $1/ndex.html;
    }
```
In html Nginx folder, I have a subfolder for each version.

Then, access to `http://localhost/0.7.0/` will get the correct content (at `/usr/share/nginx/html/0.7.0/index.html`).

The "problem" with this trick is when the browser load css/js files to run SPA, URL is set to root. So if a user refresh it will access to the main website. Is it a problem for you?
I can investigate to avoid this without result warranty (may be using the [`base`](https://router.vuejs.org/api/#base) VueRouter attribute.

**Comment by southerntofu** [comment]
> publicPath: './',

Cool! How does that work with index.html then? Is this configuration file used when building a release, to generate URLs in index.html? Otherwise i don't understand.  I had initially manually edited index.html to use relative links, but then i encountered the other problem you mentioned:

> So if a user refresh it will access to the main website.

Personally i find it an anti-feature to hijack URL client-side (unexpected behavior during refresh is frustrating on bad connections), but i understand you may have a different perspective on the matter.

> may be using the base VueRouter attribute

I'm not familiar with Vue but from the documentation it looks like precisely what we're looking for. Along with the default `index.html` route server-side (`try_files $uri /index.html =404;`) and the relative path for assets previously mentioned, i believe the entire problem will be solved!

**Comment by nioc** [comment]
As I looking for it, it seems that history mode is not compatible with `publicPath: './'` (which is used by Webpack to set href, src, path, url,... at build time): when refreshing, the entire app is broken.

So, unless I find a solution, I propose to use the default hash mode (URL will be `http://localhost/#/rooms/welcome@conference.localhost` instead of `http://localhost/rooms/welcome@conference.localhost`).
This will allow relative publicPath.

Any objection @southerntofu  @poVoq?

**Comment by licaon-kter** [comment]
Still seeing some resources with hardcoded paths that won't load when hosting in a subfolder.

Eg. https://github.com/nioc/xmpp-web/blob/cbe852cfe5f54cd7d40a7c64103417c8890d0f60/src/components/About.vue#L6

And in `manifest.json`

**Comment by nioc** [comment]
I'll look at it.

**Comment by nioc** [comment]
Thanks @licaon-kter.
I'll wait for another commit before publishing a new version. Let me know if you need it quickly.

**Comment by licaon-kter** [comment]
No rush :)
