### ISSUE TITLE
Configurable homepage route

### ISSUE THREAD

**Issue by southerntofu** [nioc/xmpp-web#23]
Currently, homepage route is for non-anonymous login. I would like to use /guest/ route as default for index.html.

**Comment by nioc** [comment]
This is a very specific usage 😆.

But may be I can set the routes according to a `local.js` variable to allow or not routes/components for:
- guests,
- registered users.

**Comment by southerntofu** [comment]
> This is a very specific usage laughing.

For the moment it is indeed. But a lot of people just want a chatroom for guests, for example for discussion around a free-software projects. Moderators already have a desktop/TUI client, but need a quick way for guest users to come and ask a question from their web browser, like many do on gitter/discord currently. Do you think it's a valid usecase?

In particular when there is no existing trust relationship between the client and the server, i find it more reasonable to disable "real" logins entirely, because we've tried for two decades now to educate users they should not give away their passwords to random services on the web ;-)

> But may be I can set the routes according to a local.js variable to allow or not routes/components

That would be perfect, thanks!

**Comment by nioc** [comment]
Agreed for the project/support use case and understanding the security argument behind your request.
May be, it will require to add some limitation/quota server side but it is another subject...

**Comment by southerntofu** [comment]
Hello and thanks for the quick release of v0.8.0! Sorry to "reopen" this issue but it appears the default route has weird behavior:

- when accessing https://anon.joinjabber.org/ directly, i end up on JID login (which is disabled in config)
- reloading that page takes me to the expected guest login page

No idea why but maybe `http://localhost/#/rooms/welcome@conference.localhost` (URI fragments for internal routes) like you mentioned in #21 could help prevent that kind of inconsistencies.

**Comment by nioc** [comment]
May be a cache issue. When I open your url, I have the nick form for guest access.

**Comment by southerntofu** [comment]
> May be a cache issue.

Thanks, that was it! Weird it happened despite explicitly asking for a no-cache refresh (ctrl + f5). Thanks again for the quick release, take care
