### ISSUE TITLE
Backlink to guest rooms view and in emoji picker

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#26]
Would be nice to have a back-link for the guest MUC view to allow people to go back to the rooms overview.

Also the emoji picker can only be quit by pressing the escape key or by selecting a emoji, but there is no way to quit it via the GUI.

Thanks!

**Comment by nioc** [comment]
Ok for button leading back to rooms list.

For the emoji, I'm sorry but the picker uses a [tabs Buefy component](https://buefy.org/documentation/tabs), and it is not easy to add a button before or after tabs lists and I prefer avoiding to much complexity (CSS tricks with absolute position is such a pain). User should press escape or select an emoji and remove it after, not a big deal.
