### ISSUE TITLE
MUC participant list with too many users breaks layout

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#36]
If I join for example the disroot@chat.disroot.org MUC get a really long line of user avatars and the entire browser window needs to be scrolled horizontally to reach the room settings etc.

**Comment by nioc** [comment]
Hello @poVoq, can you post a screenshot?

**Comment by poVoq** [comment]
![grafik](https://user-images.githubusercontent.com/940360/121508281-f3796100-c9d4-11eb-8d92-7be9f5c33097.png)

With the 100+ users in that room you can scroll horizontally really far before you reach the room settings.

**Comment by nioc** [comment]
@poVoq fixed in 0.8.2.
