### ISSUE TITLE
If `hasRegisteredAccess` is not set login widget is missing

### ISSUE THREAD

**Issue by licaon-kter** [nioc/xmpp-web#37]
Acording to https://github.com/nioc/xmpp-web#configuration `hasRegisteredAccess` has default value of `true` so I'd expect it to be `true` if I omit it from **local.js**

Yet, if I omit it the screen stays dark and I can't login, there's no input box at all.

0.8.2 Firefox

**Comment by nioc** [comment]
Hello, there is a `true` default value in `local.js` (also set in docker entrypoint)
If you remove it, there is no more default value ^^

**Comment by licaon-kter** [comment]
That's not what "default" means...

**Comment by nioc** [comment]
Okay, but why you want to remove the _default_ value from `local.js`?

**Comment by licaon-kter** [comment]
Not sure I follow, isn't `local.js` **my** config file?
