### ISSUE TITLE
JID does not change with anonymous access

### ISSUE THREAD

**Issue by freize** [nioc/xmpp-web#42]
Hello. Help me please. Maybe I'm doing something wrong, I did not find a guide on this issue.
If several people enter at the same time through an anonymous login, then the one who entered later throws out the one who entered earlier from the conference. JID remains the same. Can this be fixed somehow?

**Comment by nioc** [comment]
Hello @freize it is an XMPP settings, I just tested the 2 following scenarios with Prosody 0.11.7 as XMPP server:

- 2 different nicknames:
    1. Anonymous user enter to room with shared link (http://localhost/#/guest?join=welcome%40conference.localhost) with name `bob` 
    2. Another anonymous user enter to room with shared link (http://localhost/#/guest?join=welcome%40conference.localhost) with name `jon`
    3. The two users are in the room (✅ as expected)

- 2 identical nicknames:
    1. Anonymous user enter to room with shared link (http://localhost/#/guest?join=welcome%40conference.localhost) with name `bob` 
    2. Another anonymous user enter to room with shared link (http://localhost/#/guest?join=welcome%40conference.localhost) with name `bob` too
    3. The second user has a message explaining nickname is already used in this room and he is redirected to the nickname form (✅ as expected):
![image](https://user-images.githubusercontent.com/5225411/153765725-09945c34-2792-45c4-9a25-63db05947f68.png)

You should see an XML response from XMPP server containing a **conflict error** (which is handled by stanza and this app), like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<presence xmlns="jabber:client" type="error" to="zcjafhkdavpgytpa@anon.localhost/Web XMPP" from="welcome@conference.localhost/bob" id="7354b5ae-797f-4e3a-b827-ed25e645b0b2">
   <error code="409" type="cancel">
      <conflict xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
   </error>
   <x xmlns="http://jabber.org/protocol/muc" />
</presence>
```

I can not help you as it is an XMPP configuration issue. Here is a MUC declaration example in prosody.cfg:
```
Component "conference.domain-xmpp.ltd" "muc"
    modules_enabled = {
        "muc_mam";
        "vcard_muc";
    }
    name = "Conferences server"
    restrict_room_creation = "local"
    max_history_messages = 50
```
