### ISSUE TITLE
Update stack

### ISSUE THREAD

**Issue by nioc** [nioc/xmpp-web#45]
Move to vue 3 and official router & store.
Replace webpack with Vite.

**Comment by nioc** [comment]
If anyone knows how to package **stanza** lib with rollup, I would be so happy… it is the last piece for releasing a fresh stack (working with vite `npm run dev` rendering)

**Comment by nioc** [comment]
So after 20 days of unsuccessful tries, I choose to replace `Stanza` with `@xmpp/client`. It is a huge work to adapt code and it will take time, but you can track progress (I'll update this comment during development):

- [x] connect (authenticate)
- [x] disconnect
- [x] getRoster
- [x] sendPresence
- [x] sendMessage
- [x] onChat
- [ ] onGroupchat
- [ ] onPresence
- [ ] onMuc:join
- [ ] onMessage:sent
- [ ] onChat:state
- [ ] onMessage:sent
- [ ] onMessage:sent
- [ ] onMessage:sent
- [ ] enableCarbons
- [ ] getBookmarks
- [ ] searchHistory
- [ ] joinRoom
- [ ] getDiscoItems
- [ ] getDiscoInfo
- [ ] getUploadService
- [ ] getUploadSlot
- [ ] addBookmark
- [ ] removeBookmark
- [ ] getRoomConfig
- [ ] configureRoom
- [ ] getVCard

Important note: **BOSH will not be supported anymore**

**Comment by nioc** [comment]
Hooray, finally update achieved! :beers:

**Comment by binarydad** [comment]
Awesome! Can't wait for the docker image!

**Comment by nioc** [comment]
I have to run some tests before releasing, but it should be tomorrow (it is 05:38 am for me, time to sleep 😴)
