### ISSUE TITLE
Capacitor for mobile apps

### ISSUE THREAD

**Issue by ThatOneCalculator** [nioc/xmpp-web#51]
If [Capacitor](https://capacitorjs.com/solution/vue) could eventually be integrated for cross-platform mobile apps, that would be awesome

**Comment by nioc** [comment]
Hello I do not understand what is the bonus for this web chat app using capacitor.
There are better natives applications like [Conversations](https://github.com/inputmice/Conversations) for Android for example.

**Comment by ThatOneCalculator** [comment]
The problem is there's nothing good that's cross-platform (iOS is severely lacking in XMPP clients) and this is one of the few good clients that support stickers

**Comment by nioc** [comment]
Thanks 😉
I let the request open, may be after I update the stack, if it does not add too much assets…

**Comment by nioc** [comment]
I'm not sure which device API should be relevant?
Installed as a PWA is not enough?

**Comment by ThatOneCalculator** [comment]
It'd mostly be the notification API (possibly the Camera API for photos and the location API for location sharing), PWA notifications are very unreliable, especially on iOS.

**Comment by nioc** [comment]
Ok, I do not know iOS :grimacing:

On Android, setup a true notifications system is a pain in the a** with firebase... also often it drains battery very quickly.
Photo capture/posting and video webRTC seems to be good ideas.

**Comment by ThatOneCalculator** [comment]
Oh yea, forgot about that ^^"

Possibly for Android, there could be a foreground service instead?

**Comment by nioc** [comment]
For the android notifications, I am pretty sure that Conversations app (which is the one I use on my Android) always be better than my app.
The first goal of this app was to cover my desktop usage (I did not found a good XMPP client on Windows/Linux), I have tried some lib like [Tauri](https://tauri.studio/) to make a real desktop app but... finally, PWA in chromium was enough for me 😄

**Comment by ThatOneCalculator** [comment]
On my Android phone, I use blabber.im (a Conversations fork) which def does work great. 

Obviously Capacitor isn't a super high priority, but it would definitely be nice to have as a cross-platform solution :)

**Comment by virtadpt** [comment]
It would be nice because my work laptop is locked down (I can't install an XMPP client of any kind) and a reliable web client would be great.

**Comment by ThatOneCalculator** [comment]
@virtadpt not sure if you get what Capacitor is for, it's for building native mobile apps for iOS and Android, nothing to do with desktop usage ^^"

**Comment by virtadpt** [comment]
You're right, I didn't.  Sorry about that.

**Comment by nioc** [comment]
@virtadpt You can ["install"](https://support.google.com/chrome/answer/9658361) XMPP Web (as it is a PWA) in your desktop with Chrome/Chromium:

![image](https://user-images.githubusercontent.com/5225411/216796171-867363c5-7782-4ffa-bd34-a3a0b4d7b227.png)
 
@ThatOneCalculator I close the issue as, obviously, it will never be handled.
