### ISSUE TITLE
Cannot log in when running docker version 9.0

### ISSUE THREAD

**Issue by binarydad** [nioc/xmpp-web#53]
I'm using the same docker script as the previous version. Let me know how I can help with troubleshooting. Thanks!!

```
sudo docker run -d -p 9200:80 -e APP_HTTP=https://xmpp.mydomain.com:5443/bosh -e XMPP_HTTP=https://xmpp.mydomain.com:5443/bosh -e APP_WS=wss://xmpp.mydomain.com:5443/ws -e XMPP_WS=https://xmpp.mydomain.com:5443/ws -e APP_DEFAULT_DOMAIN=xmpp.mydomain.com --name Xmpp nioc/xmpp-web
```

![image](https://user-images.githubusercontent.com/1760607/170895141-6bbc0c62-fa3e-4abf-a36e-106991fd2c15.png)

**Comment by nioc** [comment]
Hello @binarydad, xmpp client used (xmpp.js) is different from stanza.io and does not require to use the domain part (and if you provide it, it does not meet xmpp server authentication mechanism). I forgot to mention this point in the release note...
If your xmpp domain is `xmpp.mydomain.com`, do not login with `ryan@xmpp.mydomain.com` but just `ryan`.
Try it and let me know.

**Comment by nioc** [comment]
Can you add console errors/warns/logs and/or network websocket responses for a more accurate analysis? 😉

Also, you can remove these environment variables which are [not used anymore](https://github.com/nioc/xmpp-web/commit/0458da73cbd9cc0afa1548f75f14a7d29d9e6907#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) (since BOSH is not supported by xmpp.js):
- `APP_HTTP`
- `XMPP_HTTP`

So command will become:
```
sudo docker run -d -p 9200:80
  -e APP_WS=wss://xmpp.mydomain.com:5443/ws
  -e XMPP_WS=https://xmpp.mydomain.com:5443/ws
  -e APP_DEFAULT_DOMAIN=xmpp.mydomain.com
  --name Xmpp
  nioc/xmpp-web
```

**Comment by ThatOneCalculator** [comment]
I can't login to my remote server, seems `chat.domain-web.ltd` is hardcoded?

Running with `npm run dev`

![image](https://user-images.githubusercontent.com/44733677/170897499-65efc343-8ff7-44db-9e03-a2ec9720ea31.png)
![image](https://user-images.githubusercontent.com/44733677/170897560-fbca4669-c23c-47f1-91b4-9ab6570714ff.png)

**Comment by nioc** [comment]
@ThatOneCalculator Yes it is hard-coded but in the [`local.js` file](https://github.com/nioc/xmpp-web/blob/master/public/local.js#L5).

In docker usage, is it overridden by `APP_WS` environment variable.
In archive installation, admin must set it owns values in the file as described in [README.MD](https://github.com/nioc/xmpp-web#installation).

**Comment by ThatOneCalculator** [comment]
Ah got it, thanks :)

**Comment by binarydad** [comment]
I tried that, but am still getting errors. What else can I provide? I shortened the docker args to this:

```
sudo docker run -d -p 9200:80 -e APP_WS=wss://xmpp.mydomain.com:5443/ws -e XMPP_WS=https://xmpp.mydomain.com:5443/ws -e APP_DEFAULT_DOMAIN=xmpp.mydomain.com --name Xmpp nioc/xmpp-web
```

Also, does it matter that I'm using a reverse proxy to get to the container?

![image](https://user-images.githubusercontent.com/1760607/170898719-dd10466b-3813-4fe5-a89e-f48530923d3c.png)

![image](https://user-images.githubusercontent.com/1760607/170898771-23811b35-d7fb-4c56-b0a6-52a6c230192c.png)

**Comment by nioc** [comment]
@binarydad what is the result when you login with just `ryan`?

First screenshot show that websocket is called and responds but your XMPP server replies that is a host it handles (as it is shown also in console error).

The first sent message should be something like this:
<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" xml:lang="en" **_to="xmpp.mydomain.com"_** version="1.0"/>

But in your case, it says `localhost`.

I will have a look tonight, maybe something is missing in my xmpp.js instantiation.

**Comment by nioc** [comment]
Ok I missed to instantiate domain, pull the 0.9.1 and it should be ok.

If you enter a full jid like this `user@xmpp.mydomain.com`, it will use `xmpp.mydomain.com` as XMPP domain.
If you enter a local jid like this `user`, it will use `defaultDomain` value from local.js (overriden by `APP_DEFAULT_DOMAIN` environment variable) as XMPP domain.

**Comment by binarydad** [comment]
That was it! I'm logged in. Thank you!

I see a couple other minor things, but I'll add tickets for those. 

I really love this UI. Much better than others I've seen.
