### ISSUE TITLE
Add support for low resolution screens and keypads (KaiOS)?

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#6]
Given the light weight nature of this, how about adding support for low resolution screens and keypads so that this could feasibly run on KaiOS (or the FOSS version GerdaOS)?

KaiOS is a modern fork of FirefoxOS that already runs on hundreds of millions smart feature phones in the developing world (in India it has already replaced iOS as the 2nd most common mobile operating system, and Facebook released an official WhatsApp port for it). It basically runs web-apps in it's FirefoxOS derived Gecko browser, but the screens are typically quite low resolution and without touch screens.

Thus keypad support would be needed, which would be probably also cool for Keyboard only use and for accessibility reasons.

You can easily test it with the KaiOS simulator: 
https://developer.kaiostech.com/getting-started/env-setup/simulator
Or get one of the cool retro KaiOS HMD Global Nokia branded phones :)

Official sample app in Vue: https://github.com/kaiostech/sample-vue
Edit: https://github.com/yuanwei92/kaivue or https://github.com/hqxluoyang/open

An example for a usable GUI in React is this:
https://github.com/AdrianMachado/KaiUI
And Deltachat is also being ported: https://github.com/deltachat/delta.chat-kaiOs

Thanks for considering!

Edit: might also be helpful: https://github.com/Orange-OpenSource/react-keyboard-navigation

**Comment by nioc** [comment]
Hello (again 🙂),
I used the [Bulma CSS framework](https://bulma.io/) (with Buefy for VueJS adaptation). May be some plugin/extension exists.

In your request, I see 2 points:
- adaptive for low resolution screen => this should be handled with some breakpoints in `/src/assets/styles.scss` or maybe Bulma extension.
- lack of touchscreen and keyboard navigation support => I have to check how app works with it, and may be some fix.

It is not my main priority, but project is open 🙂

**Comment by poVoq** [comment]
This might be a starting point for the breakpoint issue:
https://github.com/jgthms/bulma/issues/1677

**Comment by poVoq** [comment]
Someone is porting KaiOS GUI components to Vue:
https://github.com/LiarOnce/kaiui-vue

**Comment by nioc** [comment]
I close this since I will not handle it.

**Comment by sjehuda** [comment]
There's a a project that bring XMPP to KaiOS at https://git.disroot.org/badrihippo/convo
