### ISSUE TITLE
Instructions for compiling and running

### ISSUE THREAD

**Issue by asterismo** [nioc/xmpp-web#61]
Hi, i installed the client but there is no instructions on how to compile it. I tried myself but i cannot get the client running. Can you help me compile it? Thanks.

**Comment by asterismo** [comment]
I used "from archive" and i uncompressed files in a web folder. I think i did yarn install, npm run build... something like that

**Comment by nioc** [comment]
Archive contains the build result (statics files html, js and css) to be served with a web server like Apache or Nginx.

If you want to develop, you need to `git clone` and then:
```
npm install
npm run dev
```
