### ISSUE TITLE
Restrict public muc listing?

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#64]
Would it be possible to restrict the listing of public mucs to those of a certain muc service or virtual host?

Right now the xmpp-web users can also see the public mucs from a totally unrelated virtual host that happens to be on the same Prosody installation.

In addition it might be interesting to only show a curated list of public mucs in the overview.

**Comment by sjehuda** [comment]
Perhaps consider splitting the list into pages (e.g. 10 MUCs per page)

**Comment by nioc** [comment]
Hello @poVoq I do not understand your request (probably your use case is too complex for me 😉).

Does the @sjehuda proposal (rooms pagination on `/guest/rooms`) is answering your need?
If yes, it could be done in next release. Otherwise I will close this issue as it won't be done.

**Comment by poVoq** [comment]
Yeah that seems fine for now :)
