### ISSUE TITLE
Provide a way to insert newlines when hasSendingEnterKey is true

### ISSUE THREAD

**Issue by Ppjet6** [nioc/xmpp-web#70]
Disclaimer: I am not a user of xmpp-web myself. We've deployed it on joinjabber.org from the start and it's been of great help to our users. Thanks for developing and maintaining the project!

**Is your feature request related to a problem? Please describe.**
In many of the clients I use, Enter is used to send. I felt users would be more used to this behaviour and so I set `hasSendingEnterKey` to `true`. But I realized there is no way to insert newlines anymore as it seems Ctrl+Enter is always used to send.

**Describe the solution you'd like**
One way to insert newlines when Enter is used to send.

**Describe alternatives you've considered**
- Either swap Enter and Ctrl+Enter on `hasSendingEnterKey`,
- or introduce another key combination that will always insert newlines, such as Shift+Enter?

Shift+Enter seems to be used in other clients such as ConverseJS, Dino, etc.

**Comment by nioc** [comment]
This point of view has been discussed for many times 😉 
But with time I  consider Shift+Enter a good way of adding new line.

**Comment by nioc** [comment]
Can you confirm that `Shift`+`Enter` does not add new line? It was the expected behavior 😞 

See https://github.com/nioc/xmpp-web/issues/54#issuecomment-1141390881

> - `true`: `Control`+`Enter` and `Enter` send message, `Shift`+`Enter` add new line
> - `false`: `Control`+`Enter` send message, `Enter` and `Shift`+`Enter` add new line

**Comment by nioc** [comment]
I just checked, it works as expected for me (Firefox 109).
I close the issue, feel free to reopen it if yours users encounter issue with  `Shift`+`Enter` for new line.

**Comment by Ppjet6** [comment]
I was persuaded there was no way to do so. Sorry for the bother! Shift+Enter works indeed.
