### ISSUE TITLE
Make unimportant errors in console less prominent

### ISSUE THREAD

**Issue by Ppjet6** [nioc/xmpp-web#71]
**Is your feature request related to a problem? Please describe.**
As a dev, and with xmpp-web configured for sasl anon only, when opening the console I see lots of red. Potential tracebacks everywhere. It's "just" features for which `service-unavailable` is received.

**Describe the solution you'd like**
Most of these tracebacks could be made slightly less prominent as they're not hindering the user experience.

**Describe alternatives you've considered**
Maybe some of them can be downgraded to warning?  
I don't know if it's possible to keep them as errors without having them expanded by default so that they don't stand out as much.

**Additional context**
 For example "roster" and "bookmarks" (PEP) are probably not going to be loaded on an anonymous host, even though it's technically possible. "carbons" is not usable for sasl anon as one can't spawn another client with the same address. These are the three I get all the time.

**Comment by nioc** [comment]
Agreed to set these as warning.

**Comment by nioc** [comment]
Setup a function for handling Error: if Stanza Error it will warn, otherwise default behavior (for keeping a code error tracking).
