### ISSUE TITLE
0.9.4 fails with no error

### ISSUE THREAD

**Issue by Ppjet6** [nioc/xmpp-web#72]
**Describe the bug**
After updating to 0.9.4 from 0.9.3 (replacing all files), nothing happens with no obvious error

**To Reproduce**
1. Enter a nickname
2. Click join

**Expected behavior**

It connects and displays the list of chatrooms.

**Logs**

You can reproduce here temporarily: https://upload.anon.joinjabber.org

It seems to connect and get the list of rooms successfully but the view doesn't change.

**Application (please complete the following information):**
 - Version 0.9.4
 - XMPP Server: Prosody 0.12.1 (Debian bullseye-backports)

**Browser (please complete the following information):**
 - Device: Laptop
 - OS: Linux 6.1.x
 - Browser: Firefox nightly 111

**Comment by nioc** [comment]
Sorry, I just saw your issue, do you removed the reproducing instance (I got 404)?
Few questions:
- can you check it is not a PWA cache issue (as the app can be loaded offline, it use service worker for caching assets, but may be it is bugged and partially replace files)?
- I presume you do not see any console errors?
- problem is only on guest access (I checked main access but not guest, my bad)?

If you need a quick fix, I can publish tomorrow a 0.9.5 without the dependencies update (only your PR), which may have broke some build operation.

**Comment by Ppjet6** [comment]
https://upload.anon.joinjabber.org/ is available again now, sorry.

I have only tested for guest access yes.
It seems not to be a cache issue, I've tried on multiple profiles / browsers.
For console errors, the ones I mentioned in #71 that don't seem important.

**Comment by nioc** [comment]
I find the cause, updating vue-router version broke behavior as [mentionned in their changelog](https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22).
Fix in progress.
