### ISSUE TITLE
Add customizable registration URL to login?

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#8]
Would be cool if there was an easy way for the server admin to add a link below the login to a website that allows registration (not as in-band).

I think in-band registration is more complicated and spam-prone, thus that would be probably of lower priority.

Thanks!

**Comment by bremensaki** [comment]
Using the redirection option for IBR makes a smoother workflow, Conversations implements this well and pulls up the rego page in a web view when you attempt to register.

As a server level it's handled by eg. https://modules.prosody.im/mod_register_oob_url.html (I've never tried on ejabberd, I'd guess there's some equivalent) and provides a URL which can be pulled up as required by the client. If this exists for a given server, it's a pretty safe bet to populate a "register" link with the information.

**Comment by poVoq** [comment]
Hmm, I am not aware that this is possible with ejabberd. However, even if this is possible, it is slightly more complicated with a webclient as it first needs to connect to a BOSH server to even be able to do IBR. Thus unless the server and webclient also does XEP-0156, a simple customizable link is much easier and less fail prone (as only 50% of the xmpp servers do XEP-0156 according to the compliance tester).
