### ISSUE TITLE
Light color theme

### ISSUE THREAD

**Issue by Ppjet6** [nioc/xmpp-web#80]
**Is your feature request related to a problem? Please describe.**
I've had a report from a user asking for a light color theme. It seems the only available theme is a dark theme. While I personally appreciate it, this is an accessibility issue as they can't see much of the web client as it is.

**Describe the solution you'd like**
With a light theme, they would be able to navigate the chat more easily.

[prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) then seems to be the way to use one or the other theme automatically depending on user-preference.

**Comment by nioc** [comment]
I made a dedicated branch, with 1 commit which handle the functional part: https://github.com/nioc/xmpp-web/compare/master...light-mode

I did a light theme on another vue/bulma project by the past, it is a lot of work (dev but mostly check every component is ok with light theme)... and not enough time to handle it (as it is really not a key feature in my usage).

I close this one, feel free to reopen the previous if you think someone can do the CSS part (and tests).
