### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Ppjet6** [nioc/xmpp-web#81]
**Is your feature request related to a problem? Please describe.**
I am very foreign to the latest javascript developments, and having notes on how to start making changes to the codebase would be very helpful.

I've gone as far as running `npm install`, `npm run` telling me to run `vite` which I found in `node_modules`, this provides a local web server, then I copied local.js from public that I put in the root folder (trying things..), which worked for a time but now my changes in this file aren't picked up anymore.

I have a local prosody installed, that works fine.

**Describe the solution you'd like**
Notes either in the README or in some other file alongside indicating how to get a local setup working and how to make changes.

**Comment by nioc** [comment]
Oups, I was sure I wrote a [CONTRIBUTING.md](https://github.com/nioc/vue-dom/blob/master/CONTRIBUTING.md) like this one.

I will add it and also a dev dockerfile. In the meantime, here are the key points:

0. Install prerequisite:
  - [Node.js](https://nodejs.org/)
  - npm `npm install npm@latest -g`
  - git clone to a folder of your choice (/var/www/xmpp-web for example)
1. Access the frontend folder in a shell `cd /var/www/xmpp-web`
2. Build the project `npm install` and wait for the downloads
3. Start the vite server `npm run dev`
4. Edit local.js according to your XMPP server configuration
5. Edit the code (I suggest using VS Code)

**Comment by nioc** [comment]
@Ppjet6 I updated my contributing guide and added on this repo. Tell me if it is clear enough and easy to setup 😉
