### ISSUE TITLE
"There is no MUC serivce" when connecting as guest

### ISSUE THREAD

**Issue by singpolyma** [nioc/xmpp-web#84]
I have a `defaultMuc` service set in `local.js` but when I connect as guest instead of seeing a list of rooms I see a blank page and console says "There is no MUC service"

**Comment by nioc** [comment]
It could be obvious but does your XMPP server has a MUC service matching the value you set in `defaultMuc` config?

This is working on Prosody with a valid MUC service.

Please fill out the form to avoid me asking you what is your XMPP server and so on, thanks.

**Comment by nioc** [comment]
Also does you are logging anonymous on the same server that the one you want to use MUC service?

**Comment by singpolyma** [comment]
Ah, re-reading the readme again I guess maybe this isn't a bug but a feature request.  I would like to be able to specify what MUC service should be used to render the grid, independent of anything on the XMPP server side.
