### ISSUE TITLE
Room listing lobby for logged in users same as guest

### ISSUE THREAD

**Issue by singpolyma** [nioc/xmpp-web#85]
**Describe the solution you'd like**

It would be nice if, just like guests, logged in users could be taken to a grid of rooms in a configured MUC service.  There is now the "public rooms" but that is on their server, not my configured `defaultMuc` and it's in a compact table not the nice grid.

**Comment by nioc** [comment]
> but that is on their server, not my configured `defaultMuc`

I'm not sure to understand your use case, you set a `defaultMuc` which is not on your server? And it works? 😆

**Comment by singpolyma** [comment]
This is related to my request #84 I'd like to get that lobby view that guest sees right now, I'd like it to list MUCs based on a setting instead of based on what server the user or anon happens to be on, and I'd like it to work for registered users and guests both.

Does that sufficiently summarize the pieces?

**Comment by nioc** [comment]
If you can send me a [prosody.cfg.lua](https://github.com/nioc/xmpp-web/blob/staging-environments/docs/staging-environments/prosody-std/prosody.cfg.lua) example file which run in the staging env, it could help me to understand better 😉

**Comment by singpolyma** [comment]
It would be the same no matter what server or server config.  The whole point is it shouldn't matter how the server is configured.

**Comment by nioc** [comment]
Both guest and registered use the same `this.$xmpp.getPublicMuc()` [function](https://github.com/nioc/xmpp-web/blob/master/src/services/XmppSocket.js#L507-L551).
This function request an `iq disco#items` to find the MUC services on the host:
- defined by `anonymousHost` for guest, example: `anon.localhost`,
- found in the domain part of your username or, if not set (logged with just the local part), defined in `defaultDomain` for registered, example: `localhost`.

With the following `prosody.cfg.lua`:
``` lua
VirtualHost "localhost"
    name = "XMPP server"
    enabled = true
    -- notice that there is no disco_items as components are subdomains of virtual host

VirtualHost "anon.localhost"
    authentication = "anonymous"
    disco_items = {
        { "upload.localhost", "File upload" };
        { "anon-conference.localhost", "Multi users chat" };
}

Component "conference.localhost" "muc"
    modules_enabled = {
        "muc_mam";
        "vcard_muc";
    }
    name = "Private conferences server"
    restrict_room_creation = "local"
    max_history_messages = 50

Component "anon-conference.localhost" "muc"
    modules_enabled = {
        "muc_mam";
        "vcard_muc";
    }
    name = "Conferences server"
    restrict_room_creation = "local"
    max_history_messages = 50
```

We got the public rooms of the 2 MUC (`conference.localhost` and `anon-conference.localhost`) for registered users:
![image](https://user-images.githubusercontent.com/5225411/218344863-de77e98f-8fd6-4bdc-83d4-29d60a4361cc.png)

And guests, only see the public rooms of the advertised MUC (`anon-conference.localhost`):
![image](https://user-images.githubusercontent.com/5225411/218344912-d21f901d-ed89-4741-a6c7-5e29e1c74cc8.png)

**So, YES, server-side configuration matters.**

**If your request is only UI related**, please do not mention the configuration, and just say "_It would be nice if, just like guests, logged in users could be taken to a grid of rooms. There is now the "public rooms" but it's in a compact table not the nice grid."_

The guest grid was made after the registered table, they were not designed for the same type of use and integration (registered have the sidebar and navbar). I have to think how the grid could fit to the reduced space without losing room attributes information.
