### ISSUE TITLE
Pinned MUCs in channel-list?

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#87]
### Intended behavior

It can be a bit confusing for non-techy users to find the right place on joining first and seeing the unsorted list on channels to join. This is mainly for the guess access.

### Solution

There could be an option to pin 1-2 specific MUCs to the top of the list that are highlighted for new users to join.

Thanks!

### Priority

Should-have

### Users scope

guests

### Affected features

rooms list

### Pull request

no

**Comment by nioc** [comment]
Do you think there is a way to flag some rooms server side (through XMPP service discovery or other stuff)?

Alternatively, we can display rooms order by name in `guest/rooms` page (actually, there is no sorting rules). So XMPP admin can name them smartly for ordering 😉

**Comment by Ppjet6** [comment]
So it seems many clients actually do pinning. I've opened https://codeberg.org/joinjabber/support/issues/5 to keep track of progress in the community. There is certainly something to be done in the standard.

If we're only talking about JoinJabber, doing 469, only usable with bookmarks2, and add default bookmarks for anonymous users, I guess. As XMPP Web seems to be handling bookmarks even for guests.

**Comment by nioc** [comment]
I'm confused about set default bookmark.
Maybe, is should be easier to add a local.js attribute with pinned rooms list?

**Comment by poVoq** [comment]
Yeah, that is what I actually thought first. Simply add a comma separated list of pinned room JIDs to the xmpp-config and filter and sorting client side in JS.

Pinned default bookmarks sounds like a good idea, but AFAIK the room list is a discovery query on the default muc-component and thus has nothing to do with bookmarks directly, right?

**Comment by Ppjet6** [comment]
>  the room list is a discovery query on the default muc-component and thus has nothing to do with bookmarks directly, right?

Currently yeah that's how it's handled in XMPP Web, disco#items, but it also queries for bookmarks anyway.

> I'm confused about set default bookmark.

It's possible for the XMPP server to pre-configure a list of bookmarks for accounts.
In Prosody for example there is [mod_default_bookmarks](https://modules.prosody.im/mod_default_bookmarks.html). It doesn't seem to handle pinned bookmarks but "it shouldn't be too hard".

**Comment by nioc** [comment]
Ok, I handle a `local.js` rooms list to pinned in this issue. I will also add a room name order (I feel more comfortable with it than the "first received from server, first displayed").
If you want to explore the bookmark way, I let you open another issue (I think both approaches are interesting).
