### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [nioc/xmpp-web#9]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by poVoq** [comment]
https://github.com/legastero/stanza/blob/master/docs/Supported_XEP_Formats.md

Not all of it is implemented in the frontend though.

**Comment by nioc** [comment]
Hello @Neustradamus I'll add supported XEP/RFC list in the README.md.

**Comment by Ppjet6** [comment]
If you have a list to share I'm happy to help with writing a [DOAP file](https://xmpp.org/extensions/xep-0453.html)

**Comment by nioc** [comment]
Sadly, I do not have a reference list.
But the code comments are quite explicits, if someone can check all these XEP are truly implemented:
 - XEP-0004
 - XEP-0030
 - XEP-0045
 - XEP-0048
 - XEP-0049
 - XEP-0054
 - XEP-0059
 - XEP-0066
 - XEP-0085
 - XEP-0128
 - XEP-0156
 - XEP-0280
 - XEP-0313
 - XEP-0359
 - XEP-0363
 - XEP-0393
 - RFC 4505
 - rfc6121
